src/Entity/Module.php
<?php

namespace App\Entity;

use App\Repository\ModuleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ModuleRepository::class)]
class Module
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\ManyToOne(inversedBy: 'modules')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categorie $Categorie = null;

    #[ORM\OneToMany(mappedBy: 'module', targetEntity: ContenuSession::class, orphanRemoval: true)]
    private Collection $contenuSession;

    public function __construct()
    {
        $this->contenuSession = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->Categorie;
    }

    public function setCategorie(?Categorie $Categorie): self
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    /**
     * @return Collection<int, ContenuSession>
     */
    public function getContenuSession(): Collection
    {
        return $this->contenuSession;
    }

    public function addContenuSession(ContenuSession $contenuSession): self
    {
        if (!$this->contenuSession->contains($contenuSession)) {
            $this->contenuSession->add($contenuSession);
            $contenuSession->setModule($this);
        }

        return $this;
    }

    public function removeContenuSession(ContenuSession $contenuSession): self
    {
        if ($this->contenuSession->removeElement($contenuSession)) {
            // set the owning side to null (unless already changed)
            if ($contenuSession->getModule() === $this) {
                $contenuSession->setModule(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

}

src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $place = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateDebut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateFin = null;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    private ?Formateur $formateur = null;

    #[ORM\ManyToMany(targetEntity: Stagiaire::class, inversedBy: 'sessions')]
    private Collection $inscrit;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Formation $formation = null;

    #[ORM\OneToMany(mappedBy: 'session', targetEntity: ContenuSession::class, orphanRemoval: true)]
    private Collection $contenuSession;

    public function __construct()
    {
        $this->inscrit = new ArrayCollection();
        $this->contenuSession = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPlace(): ?int
    {
        return $this->place;
    }

    public function setPlace(int $place): self
    {
        $this->place = $place;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): self
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $dateFin): self
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getFormateur(): ?Formateur
    {
        return $this->formateur;
    }

    public function setFormateur(?Formateur $formateur): self
    {
        $this->formateur = $formateur;

        return $this;
    }

    /**
     * @return Collection<int, ContenuSession>
     */
    public function getContenuSession(): Collection
    {
        return $this->contenuSession;
    }

    public function addContenuSession(ContenuSession $contenuSession): self
    {
        if (!$this->contenuSession->contains($contenuSession)) {
            $this->contenuSession->add($contenuSession);
        }

        return $this;
    }

    public function removeContenuSession(ContenuSession $contenuSession): self
    {
        $this->contenuSession->removeElement($contenuSession);

        return $this;
    }

    /**
     * @return Collection<int, Stagiaire>
     */
    public function getInscrit(): Collection
    {
        return $this->inscrit;
    }

    public function addInscrit(Stagiaire $inscrit): self
    {
        if (!$this->inscrit->contains($inscrit)) {
            $this->inscrit->add($inscrit);
        }

        return $this;
    }

    public function removeInscrit(Stagiaire $inscrit): self
    {
        $this->inscrit->removeElement($inscrit);

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(?Formation $formation): self
    {
        $this->formation = $formation;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

}

src/Form/SessionType.php
<?php

namespace App\Form;

use App\Entity\Session;
use App\Entity\Formateur;
use App\Entity\Formation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;

class SessionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name' , TextType::class, [
                'label' => 'Nom'
            ])
            ->add('place' , IntegerType::class, [
                'label' => 'Place'
            ])
            ->add('dateDebut', DateType::class, [
                'label' => 'Date de début',
                'format' => 'yyyy-MM-dd',
                'widget' => 'single_text'
            ])
            ->add('dateFin', DateType::class, [
                'label' => 'Date de fin',
                'format' => 'yyyy-MM-dd',
                'widget' => 'single_text'
            ])
            ->add('formateur', EntityType::class, [
                'label' => 'Formateur',
                'class' => Formateur::class
            ])
            ->add('formation', EntityType::class, [
                'label' => 'Formation',
                'class' => Formation::class
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Ajouter'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Session::class,
        ]);
    }
}

src/Controller/SessionController.php
<?php

namespace App\Controller;

use App\Entity\Module;
use App\Entity\Session;
use App\Entity\Stagiaire;
use App\Form\SessionType;
use App\Entity\ContenuSession;
use App\Form\ContenuSessionType;
use App\Repository\SessionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

class SessionController extends AbstractController
{
    #[Route('/session', name: 'app_session')]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $sessions = $entityManager->getRepository(Session::class)->findAll();

        return $this->render('session/index.html.twig', [
            'sessions' => $sessions,
        ]);
    }

    #[Route('/session/add', name: 'add_session')]
    #[Route('/session/{id}/edit', name: 'edit_session')]
    public function add(ManagerRegistry $doctrine, Session $session = null, Request $request): Response
    {

        if(!$session){
            $session = new Session();
        }

        $form = $this->createForm(SessionType::class, $session);
        $form->handleRequest($request);


        if($form->isSubmitted() && $form->isValid()){

            $session = $form->getData();
            $entityManager = $doctrine->getManager();
            // prepare
            $entityManager->persist($session);
            // insert into (execute)
            $entityManager->flush();

            return $this->redirectToRoute('app_session');
        }

        return $this->render('session/add.html.twig', [
            'formAddSession' => $form->createView(),
            'edit' => $session->getId()
        ]);
    }

    #[Route('/session/{idsession}/removeModuleFromSession/{idmodule}/', name: 'remove_module_from_session')]
    #[ParamConverter("session", options:["mapping" => ["idsession" => "id"]])]
    #[ParamConverter("module", options:["mapping" => ["idmodule" => "id"]])]
    public function removeModuleFromSession(ManagerRegistry $doctrine, Session $session, ContenuSession $contenuSession, Request $request): Response{
        
        $entityManager = $doctrine->getManager();
        $session->removeContenuSession($contenuSession);

        $entityManager->flush();

        return $this->redirectToRoute('info_session', ['id'=>$session->getId()]);
    }

    #[Route('/session/{idsession}/addModuleToSession/{idmodule}/', name: 'add_module_to_session')]
    #[ParamConverter("session", options:["mapping" => ["idsession" => "id"]])]
    #[ParamConverter("module", options:["mapping" => ["idmodule" => "id"]])]
    public function addModuleToSession(ManagerRegistry $doctrine, Session $session, ContenuSession $contenuSession, Request $request): Response{
        
        $entityManager = $doctrine->getManager();
        $session->addContenuSession($contenuSession);
        $entityManager->flush();

        return $this->redirectToRoute('info_session', ['id'=>$session->getId()]);
    }


    #[Route('/session/{idsession}/removeStagiaireFromSession/{idstagiaire}/', name: 'remove_stagiaire_from_session')]
    #[ParamConverter("session", options:["mapping" => ["idsession" => "id"]])]
    #[ParamConverter("stagiaire", options:["mapping" => ["idstagiaire" => "id"]])]
    public function removeStagiaireFromSession(ManagerRegistry $doctrine, Session $session, Stagiaire $stagiaire, Request $request): Response{
        
        $entityManager = $doctrine->getManager();
        $session->removeInscrit($stagiaire);
        $entityManager->flush();

        return $this->redirectToRoute('info_session', ['id'=>$session->getId()]);
    }

    #[Route('/session/{idsession}/addStagiaireToSession/{idstagiaire}/', name: 'add_stagiaire_to_session')]
    #[ParamConverter("session", options:["mapping" => ["idsession" => "id"]])]
    #[ParamConverter("stagiaire", options:["mapping" => ["idstagiaire" => "id"]])]
    public function addStagiaireToSession(ManagerRegistry $doctrine, Session $session, Stagiaire $stagiaire, Request $request): Response{
        
        $entityManager = $doctrine->getManager();
        $session->addInscrit($stagiaire);
        $entityManager->flush();

        return $this->redirectToRoute('info_session', ['id'=>$session->getId()]);
    }

    #[Route('/session/{id}', name: 'info_session')]
    // #[IsGranted("ROLE_USER")]
    public function info(ManagerRegistry $doctrine,Session $session, ContenuSession $contenuSession= null, Request $request, SessionRepository $sr): Response
    {
        $session_id = $session->getId();
        $nonInscrits = $sr->findNonInscrits($session_id);
        $nonModules = $sr->findNonModule($session_id);

        $form = $this->createForm(ContenuSessionType::class, $contenuSession);
        $form->handleRequest($request);
        
        if($form->isSubmitted() && $form->isValid()){
            
            $contenu = $form->getData();
            // On donne la session actuel dans le champ du formulaire
            $contenu->setSession($session);  

            $entityManager = $doctrine->getManager();
            // prepare
            $entityManager->persist($contenu);
            // insert into (execute)
            $entityManager->flush();

            return $this->redirectToRoute('info_session', ['id'=>$session_id]);
        }

        return $this->render('session/info.html.twig', [
            'session' => $session,
            'nonInscrits' => $nonInscrits,
            'nonModules' => $nonModules,
            'formAddContenu' => $form->createView()
        ]);
    }
}

templates/session/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout Session{% endblock %}

{% block body %}
    <div id="addPage">
        {{ form_start(formAddSession) }}
    
            {{ form_row(formAddSession.formation) }}
            {{ form_row(formAddSession.name) }}
            <div style="display: flex; margin-right: 5px;">
                <label>Date: </label>
                <div style="display: flex; width: 31.5%;">   
                {{form_widget(formAddSession.dateDebut)}}
                {{form_widget(formAddSession.dateFin) }}
                </div>
            </div>
            {{ form_row(formAddSession.formateur) }}
            {{ form_row(formAddSession.place) }}

        {{ form_end(formAddSession) }}
    </div>
{% endblock %}

templates/session/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste Sessions{% endblock %}

{% block body %}
    <div id="sessionList">
        {% for session in sessions %}
            <div>
                <div>
                    <a href="{{ path('info_session', {'id': session.id}) }}">{{ session }}</a>
                </div>
                <div>
                    <div>
                        {% for contenu in session.contenuSession %}
                            <p>{{ contenu.module.categorie.name }}</p>
                        {% endfor %}
                    </div>
                    <div><a href='{{ path('info_formation', {'id': session.formation.id}) }}'>Formation: {{ session.formation }}</a></div>
                    <div><a href='{{ path('info_formateur', {'id': session.formateur.id}) }}'>Formateur: {{ session.formateur }}</a></div>
                    <p>{{ session.dateDebut | date('d/m/Y')}} - {{ session.dateFin | date('d/m/Y')}}</p>

                    <p>Place : {{ session.inscrit | length }}/{{ session.place}}</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/session/info.html.twig
{% extends 'base.html.twig' %}

{% block title %}Info session{% endblock %}

{% block body %}
    <div id="sessionInfo">
            <div>
                <h2><a href="{{ path('info_session', {'id': session.id}) }}">{{ session }}</a></h2>
            </div>
            <div>
                <p>{{ session.formation }}</p>
                <p>{{ session.formateur }}</p>
                <p>{{ session.dateDebut | date('d-m-Y') }} - {{ session.dateFin | date('d-m-Y') }}</p>
                {# <p>{{ session.contenuSession.duree }}</p> #}

                <div id="listModuleSession">
                    <h3>Contient :</h3>
                    {% for contenu in session.contenuSession %}
                        <p><a href='{{ path('info_module', {'id': contenu.module.id}) }}'>{{contenu.module.name}} | {{contenu.duree}} min</a></a><a href="{{ path('remove_module_from_session', {'idsession': session.id, 'idmodule': contenu.module.id}) }}"><i class="fa-solid fa-trash"></i></a></p>
                    {% endfor %}

                    <h3>Ajoutez :</h3>
                    {{ form_start(formAddContenu) }}
                        {{ form_row(formAddContenu.duree) }}
                    {{ form_end(formAddContenu) }}
                </div>

                <div id="listStagiaireSession">
                    <h3>Inscrit :</h3>

                    {% for stagiaire in session.inscrit %}
                        <p><a href='{{ path('info_stagiaire', {'id': stagiaire.id}) }}'>{{stagiaire}}</a></a><a href="{{ path('remove_stagiaire_from_session', {'idsession': session.id, 'idstagiaire': stagiaire.id}) }}"><i class="fa-solid fa-trash"></i></a></p>
                    {% endfor %}

                    <h3>Non inscrit :</h3>

                    {% for stagiaire in nonInscrits %}
                        <p><a href='{{ path('info_stagiaire', {'id': stagiaire.id}) }}'>{{stagiaire}}</a><a href="{{ path('add_stagiaire_to_session', {'idsession': session.id, 'idstagiaire': stagiaire.id}) }}"><i class="fa-solid fa-plus"></i></a></p>
                    {% endfor %}
                </div>
            </div>
    </div>

{% endblock %}